package hl.base.test;

import java.sql.SQLException;

import hl.base.model.TTest;

import javax.sql.DataSource;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanHandler;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath:spring.xml" })
public class Test {
	@Autowired
	private DataSource dataSource;

	@org.junit.Test
	public void testDbutils() {
		QueryRunner run = new QueryRunner(dataSource);

		// Use the BeanHandler implementation to convert the first
		// ResultSet row into a Person JavaBean.
		ResultSetHandler<TTest> h = new BeanHandler<TTest>(TTest.class);

		// Execute the SQL statement with one replacement parameter and
		// return the results in a new Person object generated by the BeanHandler.
		try {
			TTest p = run.query("SELECT name FROM t_test WHERE name=?", h, "jason");
			System.out.println(p.getName() + "====");
			TTest t =run.insert("insert into t_test(name) values (?)", h, "ttt");
			System.out.println(t.getName() + "====");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public static void main(String[] args) {

	}

}
